### ISSUE TITLE
Flexibility in some warnings

### ISSUE THREAD

**Issue by CortesJoan** [MO2k4/CleanCode#129]
I want for example  that the warning of "This expression is too complex."  only will trigger if there are at leat 3 or 4 conditions contrary to the current 2  "This expression is too complex. (2 / 1)".

**Comment by MO2k4** [comment]
Could you check the configuration under the settings, there should already a setting to configure this behavior

**Comment by CortesJoan** [comment]
Yeah , after restarting the ide, it has appeared  Thanks
