### ISSUE TITLE
Not compatible with latest version of Rider.

### ISSUE THREAD

**Issue by gwynnPalmer** [MO2k4/CleanCode#181]
Not compatible with Rider 2023.2
I like this plugin, any chance of an update?

**Comment by MO2k4** [comment]
Yes but I am currently on vacation. Update should be there by next week

**Comment by MO2k4** [comment]
Update is waiting for the approval of Jetbrains

**Comment by MO2k4** [comment]
@gwynnPalmer Plugin should now be available :-)

**Comment by MO2k4** [comment]
@gwynnPalmer Plugin is now available
