### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by tahazayed** [MO2k4/CleanCode#2]
how to use this plugin?

**Comment by MO2k4** [comment]
Hi,

you need to install ReSharper ([Link](https://plugins.jetbrains.com/resharper)) and then install this is extension. After that you get suggestions for CleanCode in VisualStudio.

Supported Suggestions are:

* Too many dependencies - warns when a constructor has too many interfaces passed in.
* Excessive indentation - warns if a class contains members with too much indentation.
* Too many chained references - warns if an expression has too many chained statements, is potentially violating the Law of Demeter. The check will try to ignore fluent APIs - if the type returned is the same as the type invoked, it doesn't count.
* Method too long - warns when a method contains too many statements.
* Class too big - warns if a class has too many method declarations.
* Too many method parameters - warns if a method has too many parameters.
* Method name not meaningful - simple check that a method name is longer than a certain threshold.
* Method flag parameters - warns if a boolean or enum method parameter is used in an if statement with the method. This is an indication that the method has more than one responsibility.
* Condition complexity - warns if the condition in an if statement contains too many expressions.
* Hollow type names - warns if a class has a name with a suffix that is too general, e.g. Handler, Manager, Controller. The list of names is configurable.

Suggestions are made with a underline and then there is a tooltip, with more information.

**Comment by tahazayed** [comment]
@MO2k4  thank you
