### ISSUE TITLE
Unavailable for Resharper 2019.1.1

### ISSUE THREAD

**Issue by ms-lemos** [MO2k4/CleanCode#3]
Hello there! 

I just installed VS2019 and latest Resharper (2019.1.1) and I'm not finding the extension on Resharper Extensions Manager... 
I tried downloading the source code and changing the wave to 191.0.0 and pointing resharper to a local folder but to no avail. 
I'm not sure what's needed to be changed in order for it to work with the latest version of resharper

Thanks in advance for any help!

**Comment by MO2k4** [comment]
Hey,

thanks for this informatian. I updated the plugin to the latest version and new we have to wait for jetbrains for their approval.

:-)

**Comment by ms-lemos** [comment]
Awesome, thanks!

**Comment by MO2k4** [comment]
The new version is now availabe :-)

https://plugins.jetbrains.com/plugin/11677-clean-code/update/62109

**Comment by ms-lemos** [comment]
Installed, thanks!
