### ISSUE TITLE
Pipeline shield in README broken link

### ISSUE THREAD

**Issue by zedseven** [MO2k4/CleanCode#36]
Not a significant issue by any means, but I thought I'd mention it. The link in the README shield is broken:
https://dev.azure.com/mo2k4/CleanCode/_build/latest?definitionId=1?branchName=master

I suspect the second question mark is to blame, and it should likely be:
https://dev.azure.com/mo2k4/CleanCode/_build/latest?definitionId=1&branchName=master

**Comment by MO2k4** [comment]
Yeah you are right, will fix it :-)
