### ISSUE TITLE
Installation errors on ReSharper 2018.3, options inaccessible

### ISSUE THREAD

**Issue by odegroot** [MO2k4/CleanCode#4]
When installing the Clean Code-extension, I get installation errors. Afterwards, the extension runs, but I cannot edit the thresholds.

> 11:33:29.678 |E| Error resolving type JetBrains.Lifetimes.Lifetime from assembly <undefined>, request originating from assembly “JetBrains.Platform.RdCore, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”. Could not find the type by its FQN. Is assembly qualification specified? False! Is it of our own assembly? False! Is looking into referenced assemblies allowed? False! Was the qualified referenced assembly encountered during lookup? False! Tried loading an implicitly-referenced assembly? False!

[installation errors on ReSharper 2018.3.4.txt](https://github.com/MO2k4/CleanCode/files/3492183/installation.errors.on.ReSharper.2018.3.4.txt)

I'm running ReSharper 2018.3.4.
One of my colleagues runs ReSharper 2018.2.3. For him, the extension works fine.
Another colleague also runs ReSharper 2018.3.x, he gets the same errors that I do.

Some other extension had a similar error: https://resharper-support.jetbrains.com/hc/en-us/community/posts/115000462064-Error-while-installing-extensions. There, the conclusion was that the extension specified an incorrect dependency. Perhaps that is also the case here?

**Comment by MO2k4** [comment]
Hey

thanks for your feedback.

There should be a new version available soon, we need to wait for Jetbrains approval :-) 

give it a try

**Comment by odegroot** [comment]
Oh that's brilliant, thanks for the fast response!

**Comment by odegroot** [comment]
Confirmed: the Clean Code extension now installs and runs without errors for me. 👍 

(It complains about not being able to load the icon, but that doesn't hinder its usage.)
> The icon pack CleanCode;component/Resources/Icons/Settings/ThemedIcons.Settings.Generated.Xaml could not be loaded. Cannot locate resource 'resources/icons/settings/themedicons.settings.generated.xaml'.

**Comment by MO2k4** [comment]
Hi @odegroot,

i fixed the icon problem as well:

> (It complains about not being able to load the icon, but that doesn't hinder its usage.)
>
> The icon pack CleanCode;component/Resources/Icons/Settings/ThemedIcons.Settings.Generated.Xaml could not be loaded. Cannot locate resource 'resources/icons/settings/themedicons.settings.generated.xaml'.

The Update should be available soon.
