### ISSUE TITLE
Else-ifs considered nested 

### ISSUE THREAD

**Issue by odegroot** [MO2k4/CleanCode#6]
Hello, do you think it would it be feasible to consider a chain of else-ifs as _not_ nested?
> Excessive depth of nested code blocks

Currently, the following snippets counts as depth 3.

```csharp
if (day == DayOfWeek.Friday)
    Console.WriteLine("Almost there!");
else if (day == DayOfWeek.Saturday || day == DayOfWeek.Sunday)
    Console.WriteLine("WEEKEND!!");
else if (day == DayOfWeek.Monday)
    Console.WriteLine("Meh.");
```

whereas this counts as depth 1.

```csharp
if (day == DayOfWeek.Friday)
    Console.WriteLine("Almost there!");
if (day == DayOfWeek.Saturday || day == DayOfWeek.Sunday)
    Console.WriteLine("WEEKEND!!");
if (day == DayOfWeek.Monday)
    Console.WriteLine("Meh.");
```

I know that _technically_ the above is parsed as

```csharp
if (day == DayOfWeek.Friday)
    Console.WriteLine("Almost there!");
else 
{
    if (day == DayOfWeek.Saturday || day == DayOfWeek.Sunday)
        Console.WriteLine("WEEKEND!!");
    else
    {
        if (day == DayOfWeek.Monday)
            Console.WriteLine("Meh.");
    }
}
```

which explains the nesting counter, but I really don't see a chain of else-ifs as nested, in terms of code readability.

I know that a switch would make the warning go away, but converting the above code to a switch does not improve its legibility, in my opinion.

Do you think you could have a chain of `if … else if … else if … else …` counted as nesting depth 1?

Thanks for the helpful plugin!

**Comment by eitamal** [comment]
Hey @odegroot,

I don't maintain or contribute to this project, but I came across this issue and thought I'd provide my input as I can't say I agree it will be feasible to consider a chain of else-ifs as not nested. Let me explain why:

For starters, your first code-block and the 2nd one are different. While _you_ know that in this particular example, they would behave similarly, the `else` actually makes a pretty big difference. 
Say we added the following condition to the two code-blocks:
```c#
if (day == DayOfWeek.Sunday)
    Console.WriteLine("It's SUNDAY!");
```
The 1st code-block would now look like this:
```c#
if (day == DayOfWeek.Friday)
    Console.WriteLine("Almost there!");
if (day == DayOfWeek.Saturday || day == DayOfWeek.Sunday)
    Console.WriteLine("WEEKEND!!");
if (day == DayOfWeek.Monday)
    Console.WriteLine("Meh.");
if (day == DayOfWeek.Sunday)
    Console.WriteLine("It's SUNDAY!");
```
and the 2nd one like this:
```c#
if (day == DayOfWeek.Friday)
    Console.WriteLine("Almost there!");
else if (day == DayOfWeek.Saturday || day == DayOfWeek.Sunday)
    Console.WriteLine("WEEKEND!!");
else if (day == DayOfWeek.Monday)
    Console.WriteLine("Meh.");
else if (day == DayOfWeek.Sunday)
    Console.WriteLine("It's SUNDAY!");
```
If `day` happened to be `Sunday` the two above code-blocks would give different outputs (the 2nd one omitting the `"It's SUNDAY!"` output). While this might seem obvious, consider other conditions where the answer is a little less deterministic (e.g. using the `is` keyword to check if an object is an interface).

To further illustrate my point, how about we remove some of the syntactic sugar and then refactor the code in your 2nd code-block:
```c#
if (day == DayOfWeek.Friday)
    Console.WriteLine("Almost there!");
else 
{
    if (day == DayOfWeek.Saturday || day == DayOfWeek.Sunday)
        Console.WriteLine("WEEKEND!!");
    else
    {
        if (day == DayOfWeek.Monday)
            Console.WriteLine("Meh.");
    }
}
```
Following Uncle Bob's clean code, an `if` statement should only have one line, so we would have to extract all of the nestings to function calls:
```c#
if (day == DayOfWeek.Friday)
    Console.WriteLine("Almost there!"); // Already one line - nothing to do.
else 
    OutputNotFriday();

public void OutputNotFriday()
{
    if (day == DayOfWeek.Saturday || day == DayOfWeek.Sunday)
        Console.WriteLine("WEEKEND!!");  // Already one line - nothing to do.
    else
        OutputNotWeekend();
}

public void OutputNotWeekend()
{
    if (day == DayOfWeek.Monday)
            Console.WriteLine("Meh.");  // Already one line - nothing to do.
}
```

As you can see from the example above, your 2nd code-block would go through quite a bit of refactoring while your 1st code-block already adheres "the one line per `if` statement".

Lastly, in my opinion, `else if` requires more cognitive effort than `if`, from a readability standpoint, and so making the distinction between them makes sense to me.

I would also like to add that if you haven't read Uncle Bob's book, Clean Code, I would highly recommend it!
Some of the points he makes seem a bit extreme for my taste, but following most of them have made mine and my team's coding lives so much better, and he explains way better than I ever could the reasoning behind the one line code-blocks.
