### ISSUE TITLE
Warnings Reported for Protected Overrides

### ISSUE THREAD

**Issue by Mike-E-angelo** [MO2k4/CleanCode#65]
I made mention of this [in this comment](https://github.com/MO2k4/CleanCode/issues/63#issuecomment-920154866), and at the time it appeared that the issue had been addressed.  Unfortunately, it appeared that way due to [a bunch of really wonky behavior introduced in VS2022 Preview 4](https://youtrack.jetbrains.com/issue/RSRP-486030).

So, capturing it here for review.

Clean Code reports warnings for protected override members.  This is especially prevalent in Blazor applications with their `OnAfterRender*` methods.  I absolutely hate that they use a boolean flag but that's the reality of the situation, unfortunately.

![](https://i.imgur.com/zAF285d.png)

Expected: if the member is overridden, and the consumer has no control over the interface, the warning should not be displayed.

**Comment by MO2k4** [comment]
@Mike-E-angelo the new version is out, could you give it a try?

**Comment by Mike-E-angelo** [comment]
Hey @MO2k4 thank you so much for your efforts here.  I actually had this on my list of things to do today.

I can confirm that the checkbox is there and working.  It's unfortunate that more cannot be done but I understand.  If you can think of a way of mitigating `override` methods that would excellent/ideal, but in the meantime the setting works just as well. :)

Thank you again for your dedication to this project. 👍
